### ISSUE TITLE
就传这里就行

### ISSUE THREAD

**Issue by Kimetiii** [yUan44/picture#1]
抓点紧，别偷懒耍滑

**Comment by Kimetiii** [comment]
你怎么不回复我？

**Comment by yUan44** [comment]
什么完，根本不提示，停水了，妈的

**Comment by Kimetiii** [comment]
单位停水了？你这操作太鸡肋了

**Comment by yUan44** [comment]
家里停水了，现在来水了，你那封闭式教育可也行啊？该出来透透气了

**Comment by Kimetiii** [comment]
刚才还晴天，刚才打了几个雷，立马阴天下雨了

**Comment by yUan44** [comment]
吉沢明步隐退了

**Comment by Kimetiii** [comment]
她不行了，岁数太大了，现在应该有很多年轻的优质一代

**Comment by yUan44** [comment]
等待下班，回家洗澡




在2019年03月20日 10:46，Kimetiii 写道：

她不行了，岁数太大了，现在应该有很多年轻的优质一代

**Comment by Kimetiii** [comment]
**你在干嘛呢？我这边终于可以喘息一会儿了
问你个事儿：
iview树节点上面怎么才能加路由，
***也就是render函数里面加路由标签

**Comment by yUan44** [comment]
不知道啊，用组件最好少用render




在2019年03月21日 15:15，Kimetiii 写道：

**你在干嘛呢？我这边终于可以喘息一会儿了
问你个事儿：
iview树节点上面怎么才能加路由，
***也就是render函数里面加路由标签

**Comment by Kimetiii** [comment]
你上次给你写的那个类子背景什么的在哪设置，我要给他换个颜色

**Comment by yUan44** [comment]
在app.vue吧，你f12看不见吗。哥哥早都忘了写过什么了


在2019年03月21日 15:23，Kimetiii 写道：

你上次给你写的那个类子背景什么的在哪设置，我要给他换个颜色

**Comment by Kimetiii** [comment]
草，你这稍微差点意思啊，我找找吧，你现在没有活儿？

**Comment by Kimetiii** [comment]
这个东西怎么弄个提醒，研究一下

**Comment by yUan44** [comment]
有活啊，不是很多，计划之中，天气风老大了，一会下雨，一会晴天，今晚还得去打打球


在2019年03月21日 15:26，Kimetiii 写道：

草，你这稍微差点意思啊，我找找吧，你现在没有活儿？

**Comment by Kimetiii** [comment]
我们单位跟电信有活动，一个月30块钱不限流量还有500分钟全国通话

**Comment by yUan44** [comment]
弄什么提醒？


在2019年03月21日 15:26，Kimetiii 写道：

这个东西怎么弄个提醒，研究一下

**Comment by Kimetiii** [comment]
现在天天打球了？今天南京风挂的吓人，很大

**Comment by Kimetiii** [comment]
github提醒啊，但是我那个傻逼三星手机不支持电信，我是真想换个号

**Comment by yUan44** [comment]
那个5277不要了呗


在2019年03月21日 15:29，Kimetiii 写道：

github提醒啊，但是我那个傻逼三星手机不支持电信，我是真想换个号

**Comment by yUan44** [comment]
邮箱提醒啊，我都是邮箱回复你的，来条消息手机就响一下


在2019年03月21日 15:29，Kimetiii 写道：

github提醒啊，但是我那个傻逼三星手机不支持电信，我是真想换个号

**Comment by Kimetiii** [comment]
是不想要了，一个月50太贵了，我基本还不用网，也不打电话，白掏钱谁干，应该是有提醒的看你邮箱

**Comment by Kimetiii** [comment]
我上不了邮箱，草

**Comment by yUan44** [comment]
那你就2分钟刷一下页面
在2019年03月21日 15:32，Kimetiii 写道：

我上不了邮箱，草

**Comment by Kimetiii** [comment]
我写个shell脚本放浏览器上吧

**Comment by Kimetiii** [comment]
你现在用的什么电话卡，什么资费

**Comment by Kimetiii** [comment]
> 那你就2分钟刷一下页面 在2019年03月21日 15:32，Kimetiii 写道： 我上不了邮箱，草 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你怎么老这么写，在我写的基础上写

**Comment by yUan44** [comment]
我是回复你的啊


在2019年03月21日 15:36，Kimetiii 写道：

那你就2分钟刷一下页面 在2019年03月21日 15:32，Kimetiii 写道： 我上不了邮箱，草 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你怎么老这么写，在我写的基础上写

**Comment by yUan44** [comment]
我现在移动卡啊，套餐1G流量，38一个月好像

**Comment by Kimetiii** [comment]
1G够用吗

**Comment by yUan44** [comment]
够了啊，上班，家里都有WiFi，出去玩怎么也够了

**Comment by Kimetiii** [comment]
我周末去看看卡，上次想办个校园卡，妈的要学生证

**Comment by Kimetiii** [comment]
又他妈加班，你今晚能吃鸡吗？九点半

**Comment by yUan44** [comment]
今晚怎么事？
你加班还吃什么鸡

**Comment by yUan44** [comment]
明天去驾校报名，五一想去找你玩 太穷了妈的，去不了
五一放四天了，国务院发声明了，你可以看看

**Comment by Kimetiii** [comment]
我要问你的问题在另一个仓库里，五一要不放几天？你好好看看加班是昨天的事，今天我已经开始完全接管后台了，又是加表又是加逻辑，我慌得一批，前台他妈还是我搞，之前后台那个人估计要撤了

**Comment by Kimetiii** [comment]
你俩五一过来赶紧进买票，坐高铁过来便宜，四个小时还方便

**Comment by yUan44** [comment]
飞机也才不到400

**Comment by yUan44** [comment]
俩小时不到

**Comment by yUan44** [comment]
看看她五一回不回家吧

**Comment by Kimetiii** [comment]
回家你自己过来呗，多爽

**Comment by Kimetiii** [comment]
你他吗看一眼我的问题啊，在你另一个仓库里面

**Comment by yUan44** [comment]
我他吗回复你了，自己去看吧

**Comment by yUan44** [comment]
这干拖不到底，聊得有点长了，滚动条都小了
