### ISSUE TITLE
新的一周，新的问题

### ISSUE THREAD

**Issue by Kimetiii** [yUan44/picture#2]
上次跟你说的那个前台画树需要一个：根据父节点查询数据的接口，你说在前台加判断，具体怎么加啊，现在情况就是我返回的接口是根据用户名查询数据，返回了一个数组

**Comment by Kimetiii** [comment]
刚哥，求助！

**Comment by yUan44** [comment]
在这啊，找到了

**Comment by yUan44** [comment]
哥哥这周开始忙了

**Comment by yUan44** [comment]
准备冲个季度奖了2400

**Comment by yUan44** [comment]
每天多加一小时，就可以多1800

**Comment by Kimetiii** [comment]
正好可以给我买个新款的ipad mini

**Comment by yUan44** [comment]
数组什么结构的

**Comment by yUan44** [comment]
你第一层循环判断有没有子菜单，有再循环一个，没有跳过continue

**Comment by Kimetiii** [comment]
{
      "id": "8a062c5b69c203de0169c359330901f6",
      "directoryName": "小秃驴",
      "type": "product",
      "extendId": "8a062c5b69c203de0169c3592a990185",
      "parentNodeId": "string",
      "createTime": "2019-03-28T16:09:56.744+0800",
      "createOperator": "WX652885",
      "updateTime": "2019-03-28T16:15:00.454+0800",
      "updateOperator": "WX652885",
      "extendedInformation": null,
      "versionName": null
    },

**Comment by yUan44** [comment]
这个没有子菜单啊，哪个字段能体现出来

**Comment by Kimetiii** [comment]
数据库里面有子菜单这个概念

**Comment by Kimetiii** [comment]
没有

**Comment by yUan44** [comment]
那怎么知道有没有子菜单
